### ISSUE TITLE
diff_transformer.py is not available inside the directry it referenced

### ISSUE THREAD

**Issue by mahendraphd** [steventan0110/DiffNorm#1]
from fairseq.models.text_to_speech.diff_transformer import (
ModuleNotFoundError: No module named 'fairseq.models.text_to_speech.diff_transformer'

While trying to run the code getting above module not found error (diff_transformer) form where oi imports two classes     DiffusionTransformerModel and base_s2st_transformer_encoder_architecture .

After inspection i found that this   diff_transformer.y is not present in the dir, i also  checked in fairseq liberary also not present there.
Please update this file in the repository or provide any source form where i can ge that python file.
Thank you.

**Comment by steventan0110** [comment]
@mahendraphd  Thanks for spotting the issue. I previously removed that file because it is not actually used, but apparantly the argument processing requires this outdated file. The file is now pushed to the repo and you can find in this commit: https://github.com/steventan0110/DiffNorm/commit/f7e9426147a78132549f5c640cf247cf7e45dcca
